apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nbvh-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: bug.161.35.220.22.nip.io
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: helloapp-nbvh-nohost-svc
                port:
                  number: 8080
    - host: demo.161.35.220.22.nip.io
      http:
        paths:
          - path: /host/?(.*)
            pathType: Prefix
            backend:
              service:
                name: helloapp-nbvh-host-svc
                port:
                  number: 80
          - path: /echo/?(.*)
            pathType: Prefix
            backend:
              service:
                name: helloapp-nbvh-echo-svc
                port:
                  number: 8080
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: helloapp-nbvh-dumpster-svc
                port:
                  number: 80
